# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Music.create(:song_name => "Black Strobe - Boogie In Zero Gravity (Extended Version)",:song_api => "https://soundcloud.com/arnaudrebotini/01-black-strobe-boogie-in",:genre => "Electronic",:artist => "Arnaud Rebotini")
Music.create(:song_name => "Colours (GTA V Soundtrack)",:song_api => "https://soundcloud.com/ageofconsent/colours-gta-v-soundtrack",:genre => "Electronic",:artist => "ageofconsent")
Music.create(:song_name => "Com Truise - Data Kiss",:song_api => "https://soundcloud.com/ghostly/com-truise-data-kiss",:genre => "Electronic",:artist => "ghostly")
Music.create(:song_name => "iamamiwhoami; y (Moby remix)",:song_api => "https://soundcloud.com/twimclabel/iamamiwhoami-y-moby-remix",:genre => "Electronic",:artist => "To whom it may concern.")
Music.create(:song_name => "Nowhere To Go",:song_api => "https://soundcloud.com/nite-jewel/nowhere-to-go",:genre => "Electronic",:artist => "Nite Jewel")
Music.create(:song_name => "STRFKR - While I'm Alive",:song_api => "https://soundcloud.com/polyvinyl-records/starfucker-while-im-alive",:genre => "Pop",:artist => "Polyvinyl Records")
Music.create(:song_name => "Monsters",:song_api => "https://soundcloud.com/ruellemusic/monsters-master-2",:genre => "Pop",:artist => "Ruelle")
Music.create(:song_name => "Big Data Dangerous",:song_api => "https://soundcloud.com/bigbeatparis/big-data-dangerous",:genre => "Electronic",:artist => "Big Beat Paris")
Music.create(:song_name => "Big Data - The Business Of Emotion (LEFTI Remix)",:song_api => "https://soundcloud.com/bigdatabigdata/the-business-of-emotion-feat-white-sea-lefti-remix",:genre => "Electronic",:artist => "Big Data")
Music.create(:song_name => "The Black Keys: Tighten Up",:song_api => "https://soundcloud.com/gaga-digi/the-black-keys-tighten-up",:genre => "Pop",:artist => "gaga")
Music.create(:song_name => "Cheap Thrills - Fake Shark",:song_api => "https://soundcloud.com/glowinthehaze/cheap-thrills-fake-shark",:genre => "Indie",:artist => "glowinthehaze")
Music.create(:song_name => "Bad Books - Forest Whitaker",:song_api => "https://soundcloud.com/triplecrownrecords/forest-whitaker-by-bad-books",:genre => "Indie",:artist => "triplecrownrecords")
Music.create(:song_name => "Oxford Comma",:song_api => "https://soundcloud.com/antmn23/02-oxford-comma",:genre => "Indie",:artist => "antmn23")
Music.create(:song_name => "40 Day Dream",:song_api => "https://soundcloud.com/edward-sharpe-mag-zeros/40-day-dream",:genre => "Indie",:artist => "Edward Sharpe Mag Zeros")
Music.create(:song_name => "Grouplove - Ways to Go",:song_api => "https://soundcloud.com/canvasback/grouplove-ways-to-go",:genre => "Indie",:artist => "Canvasback")
Music.create(:song_name => "Gigamesh - Don't Stop ft. Jana Nyberg",:song_api => "https://soundcloud.com/gigamesh/gigamesh-dont-stop-version-2-0",:genre => "Electronic",:artist => "GIGAMESH")
Music.create(:song_name => "All I Heard",:song_api => "https://soundcloud.com/futureclassic/mitzi-all-i-heard-2",:genre => "Indie",:artist => "future classic")
Music.create(:song_name => "Like It Was",:song_api => "https://soundcloud.com/futureclassic/like-it-was",:genre => "Indie",:artist => "future classic")
Music.create(:song_name => "Truly Alive",:song_api => "https://soundcloud.com/futureclassic/mitzi-truly-alive-2",:genre => "Indie",:artist => "future classic")
Music.create(:song_name => "Heartbreak",:song_api => "https://soundcloud.com/ageofconsent/heartbreak-single",:genre => "Electronic",:artist => "ageofconsent")
Music.create(:song_name => "Rawnald Gregory Erickson the Second",:song_api => "https://soundcloud.com/starfucker_usa/rawnald-gregory-erickson-the-second",:genre => "Indie",:artist => "STRFKR")
Music.create(:song_name => "Hellogoodbye - (Everything Is) Debatable",:song_api => "https://soundcloud.com/oldfriendsrecords/hellogoodbye-everything-is",:genre => "Indie",:artist => "Old Friends Records")
Music.create(:song_name => "Atlas Genius - Trojans",:song_api => "https://soundcloud.com/warnerbrosrecords/atlas-genius-trojans-1",:genre => "Alternative",:artist => "WarnerBrosRecords")
Music.create(:song_name => "Giants",:song_api => "https://soundcloud.com/bearhandsband/giants",:genre => "Rock",:artist => "Bear Hands")
Music.create(:song_name => "Carried Away",:song_api => "https://soundcloud.com/passionpit/carried-away",:genre => "Alternative",:artist => "passionpit")
Music.create(:song_name => "Lisztomania",:song_api => "https://soundcloud.com/glassnotemusic/lisztomania",:genre => "Alternative",:artist => "Glassnote Records")
Music.create(:song_name => "Cold Cold Man",:song_api => "https://soundcloud.com/saintmotel/cold-cold-man",:genre => "Alternative",:artist => "saintmotel")
Music.create(:song_name => "Soul meets Body",:song_api => "https://soundcloud.com/taco-supreme/soul-meets-body-instrumental",:genre => "Hiphop",:artist => "Taco Supreme")
Music.create(:song_name => "Mike Snow - Animal",:song_api => "https://soundcloud.com/downtownrecords/mike-snow-animal",:genre => "Pop",:artist => "Downtown Records")
Music.create(:song_name => "Houdini",:song_api => "https://soundcloud.com/fosterthepeoplemusic/houdini",:genre => "Alternative",:artist => "Foster The People")
Music.create(:song_name => "Kids",:song_api => "https://soundcloud.com/whoismgmt/kids",:genre => "Pop",:artist => "whoismgmt")
Music.create(:song_name => "My Type",:song_api => "https://soundcloud.com/saintmotel/saint-motel-my-type",:genre => "Pop",:artist => "saintmotel")
Music.create(:song_name => "Stepping Stone",:song_api => "https://soundcloud.com/hiddentrackmusic/23-lemaitre-stepping-stone-feat-mark-johns",:genre => "Electronic",:artist => "Lemaitre")
Music.create(:song_name => "Tearing Me Up",:song_api => "https://soundcloud.com/the-bob-moses/tearing-me-up-1",:genre => "Electronic",:artist => "Bob Moses")
Music.create(:song_name => "Kyla La Grange - Cut Your Teeth (Kygo Remix)",:song_api => "https://soundcloud.com/kygo/kyla-la-grange-cut-your",:genre => "Electronic",:artist => "Kygo")
Music.create(:song_name => "Rather Be Feat. Jess Glynne",:song_api => "https://soundcloud.com/cleanbandit/rather-be-feat-jess-glynne",:genre => "Electronic",:artist => "Clean Bandit")
Music.create(:song_name => "Carousel - Let's Go Home (Sound Remedy Remix)",:song_api => "https://soundcloud.com/soundremedy/carousel-lets-go-home-soundremedy",:genre => "Electronic",:artist => "Sound Remedy")
Music.create(:song_name => "Am I Wrong - Envy",:song_api => "https://soundcloud.com/djchanos/am-i-wrong-envy-original-mix",:genre => "Pop",:artist => "Nico & Vinz")
Music.create(:song_name => "Fall Out Boy Centuries Final POP MIX",:song_api => "https://soundcloud.com/republicrecords/fall-out-boy-centuries-final-pop-mix",:genre => "Pop",:artist => "RepublicRecords")
Music.create(:song_name => "Wait On Me",:song_api => "https://soundcloud.com/superduperkylemusic/wait-on-me",:genre => "Pop",:artist => "KYLE.")
Music.create(:song_name => "Ashley Monroe - On To Something Good",:song_api => "https://soundcloud.com/wmnashville/ashley-monroe-on-to-something-good",:genre => "Indie",:artist => "Warner Music Nashville")
Music.create(:song_name => "Calvin Harris & John Newman - Blame (R3hab Remix)",:song_api => "https://soundcloud.com/r3hab/calvin-harris-john-newman-blame-r3hab-remix",:genre => "Pop",:artist => "R3HAB")
Music.create(:song_name => "Pitbull - Time Of Our Lives Ft. Ne-Yo",:song_api => "https://soundcloud.com/pitbull/pitbull-time-of-our-lives-ft-ne-yo",:genre => "Pop",:artist => "Pitbull")
Music.create(:song_name => "Mr. Probz - Nothing Really Matters (Kav Verhouzer Remix)",:song_api => "https://soundcloud.com/kavverhouzer/mr-probz-nothing-really-matters-kav-verhouzer-remix",:genre => "DeepHouse",:artist => "KAV VERHOUZER")
Music.create(:song_name => "Lights - Up We Go (Knight One Remix)",:song_api => "https://soundcloud.com/knightone/lights-up-we-go-knight-one-remix",:genre => "Pop",:artist => "Knight One")
Music.create(:song_name => "Hold On Tight",:song_api => "https://soundcloud.com/edprosek/hold-on-tight",:genre => "Alternative",:artist => "Ed Prosek")
Music.create(:song_name => "Zedd ft. Selena Gomez - I Want You To Know (Cover) (Dunisco & SJUR ft. JeyJeySax Remix)",:song_api => "https://soundcloud.com/officialsjur/i-want-you-to-know-dunisco-sjur-ft-jeyjeysax-remix",:genre => "Pop",:artist => "SJUR")
Music.create(:song_name => "Uptown Funk - Mark Ronson ft. Bruno Mars (Max Schneider & Mike Tompkins Cover)",:song_api => "https://soundcloud.com/nslhnciftci/uptown-funk-mark-ronson-ft-bruno-mars-max-schneider-mike-tompkins-cover",:genre => "Pop",:artist => "nslhnciftci")
Music.create(:song_name => "Betablock3r - In My Head (Televisor Remix)",:song_api => "https://soundcloud.com/televisormusic/betablock3r-in-my-head-televisor-remix-1",:genre => "Pop",:artist => "Televisor (Official)")
Music.create(:song_name => "POWERS - Beat Of My Drum (The White Panda Remix)",:song_api => "https://soundcloud.com/whitepandamusic/beat-of-my-drum-white-panda-remix",:genre => "Pop",:artist => "whitepandamusic")
Music.create(:song_name => "Jasmine Thompson - Adore (Addal Remix)",:song_api => "https://soundcloud.com/addal/jasmine-thompson-adore-addal",:genre => "Pop",:artist => "ADDAL")
Music.create(:song_name => "Harold van Lennep - Liberation [OUT NOW!]",:song_api => "https://soundcloud.com/bearded-man-recordings/harold-van-lennep-liberation-1",:genre => "DeepHouse",:artist => "The Bearded Man")
Music.create(:song_name => "Between the Devil and the Deep Blue Sea",:song_api => "https://soundcloud.com/xylo100/between-the-devil-and-the-deep-blue-sea",:genre => "Pop",:artist => "XYLØ")
Music.create(:song_name => "Feathers & Wax",:song_api => "https://soundcloud.com/vicktortaiwo/feathers-and-wax",:genre => "DeepHouse",:artist => "vicktor taiwò")
Music.create(:song_name => "Dropout - Slowly ",:song_api => "https://soundcloud.com/edm/id-slowly-edm-com-premiere",:genre => "EDM",:artist => "EDM.com")
Music.create(:song_name => "Jason Derulo - Want To Want Me (Remix)",:song_api => "https://soundcloud.com/speakerofthehouse/derulospeakerremix",:genre => "DeepHouse",:artist => "Speaker of the House")
Music.create(:song_name => "Shut Up And Dance - Walk The Moon (Devin & Kyle Cover)",:song_api => "https://soundcloud.com/raczeek/shut-up-and-dance-walk-the-moon-devin-kyle-cover",:genre => "Pop",:artist => "Raczek")
Music.create(:song_name => "Jasmine Thompson - Thinking Out Loud || Mankel Remix",:song_api => "https://soundcloud.com/mankelmusic/jasmine-thompson-thinking-out-loud-mankel-remix",:genre => "Pop",:artist => "Jasmine Thompson")
Music.create(:song_name => "Thinking Out Loud (Cavaro Remix) ",:song_api => "https://soundcloud.com/cavaroofficial/thinking-out-loud-cavaro-remix-ed-sheeran-1",:genre => "Pop",:artist => "Ed Sheeran")
Music.create(:song_name => "Muse - Madness",:song_api => "https://soundcloud.com/pablokane/muse-madness",:genre => "AlternativeRock",:artist => "Pablo Morano")
Music.create(:song_name => "Mr Probz - Waves Remix",:song_api => "https://soundcloud.com/splifbeatz/mr-probz-waves-remix",:genre => "Electronic",:artist => "Splifbeatz")
Music.create(:song_name => "Ellie Goulding - High For This (Kygo Remix)",:song_api => "https://soundcloud.com/kygo/ellie-goulding-high-for-this",:genre => "Pop",:artist => "Kygo")
Music.create(:song_name => "George Ezra - Budapest (Official A2A RMX)",:song_api => "https://soundcloud.com/a2amusic/george-ezra-budapest-a2a-remix",:genre => "DeepHouse",:artist => "George Ezra")
Music.create(:song_name => "All Of Me",:song_api => "https://soundcloud.com/johnlegend/all-of-me-3",:genre => "AlternativeRock",:artist => "johnlegend")
Music.create(:song_name => "Calvin Harris - Summer ",:song_api => "https://soundcloud.com/calvinharris/calvin-harris-summer-extended",:genre => "Electronic",:artist => "Calvin Harris")
Music.create(:song_name => "Coldplay - Midnight (Kygo Remix)//Pete Tong BBC Radio 1 Snippet",:song_api => "https://soundcloud.com/kygo/coldplay-midnight-kygo-remixpete-tong-bbc-radio-1-snippet",:genre => "DeepHouse",:artist => "Kygo")
Music.create(:song_name => "Coldplay - Midnight (Giorgio Moroder Remix)",:song_api => "https://soundcloud.com/giorgiomoroder/coldplay-midnight-giorgio-moroder-remix",:genre => "DiscoHouse",:artist => "Kygo")
Music.create(:song_name => "Rude - Magic (Cover)",:song_api => "https://soundcloud.com/mrcarlomendoza/rude-magic-cover",:genre => "Indie",:artist => "Magic")
Music.create(:song_name => "Thomas Jack Presents: Kygo - Tropical House Vol.6",:song_api => "https://soundcloud.com/thomasjackmusic/thomas-jack-presents-tropical-house-vol6-with-kygo",:genre => "DeepHouse",:artist => "Kygo")
Music.create(:song_name => "Echosmith - Cool Kids",:song_api => "https://soundcloud.com/upcastmusic/echosmith-cool-kids",:genre => "Indie",:artist => "Upcast Music")
Music.create(:song_name => "Ella Henderson - Ghost (Oliver Nelson Remix)",:song_api => "https://soundcloud.com/nickraymondg/ella-henderson-ghost-oliver-nelson-remix",:genre => "Disco",:artist => "Thissongissick.com")
Music.create(:song_name => "Martin Garrix & Bebe Rexha - In The Name Of Love",:song_api => "https://soundcloud.com/martingarrix/itnol",:genre => "EDM",:artist => "Martin Garrix")
Music.create(:song_name => "The Chainsmokers Ft. Halsey - Closer (GhostDragon Remix)",:song_api => "https://soundcloud.com/djghostdragon/tcsclosergdedit",:genre => "EDM",:artist => "GhostDragon")
Music.create(:song_name => "Flume - Say It ft. Tove Lo (Illenium Remix)",:song_api => "https://soundcloud.com/illeniumofficial/flume-say-it-ft-tove-lo-illenium-remix",:genre => "EDM",:artist => "ILLENIUM (Official)")
Music.create(:song_name => "Galantis & Hook N Sling - Love On Me",:song_api => "https://soundcloud.com/wearegalantis/loveonme",:genre => "EDM",:artist => "Galantis")
Music.create(:song_name => "Martin Garrix & Mesto - WIEE",:song_api => "https://soundcloud.com/martingarrix/wiee",:genre => "EDM",:artist => "Martin Garrix")
Music.create(:song_name => "Let Me Love You - Justin Bieber (Trap Edit)",:song_api => "https://soundcloud.com/blosshouse/let-me-love-you-justin-bieber-trap-edit",:genre => "EDM",:artist => "Bloss House")
Music.create(:song_name => "Martin Garrix - Sun Is Never Going Down (feat. Dawn Golden)",:song_api => "https://soundcloud.com/martingarrix/sun-is-never-going-down",:genre => "EDM",:artist => "Martin Garrix")
Music.create(:song_name => "Taylor Girlz_Steal Her Man_Bol",:song_api => "https://soundcloud.com/taylor-girlz/taylor-girlz_steal-her-man_bol",:genre => "EDM",:artist => "TAYLOR GIRLZ")
Music.create(:song_name => "ONE DANCE -- DRAKE (feat. Wizkid & Kyla)",:song_api => "https://soundcloud.com/zizo_h0/one-dance-drake-feat-wizkid-kyla",:genre => "EDM",:artist => "zizo_Oo")
Music.create(:song_name => "Cheat Codes & Dante Klein - Let Me Hold You (Turn Me On)",:song_api => "https://soundcloud.com/spinninrecords/cheat-codes-dante-klein-let-me-hold-you-turn-me-on",:genre => "EDM",:artist => "Spinnin' Records")
Music.create(:song_name => "Tomsize x Twenty One Pilots - Stressed Out",:song_api => "https://soundcloud.com/tomsize/twenty-one-pilots-stressed-out-tomsize-remix",:genre => "EDM",:artist => "TOMSIZE")
Music.create(:song_name => "Sia - Cheap Thrills Ft. Sean Paul (Bruno Torres Remix)",:song_api => "https://soundcloud.com/bruno-torres-remixes/sia-cheap-thrills-ft-sean-paul-bruno-torres-remix",:genre => "EDM",:artist => "Bruno Torres Remixes")
Music.create(:song_name => "Calvin Harris & Rihanna - This Is What You Came For(R3hab & Henry Fong Remix)",:song_api => "https://soundcloud.com/r3hab/calvin-harris-this-is-what-you-came-for-r3hab-henry-fong-remix",:genre => "EDM",:artist => "R3HAB")
Music.create(:song_name => "I Took a Pill in Ibiza (Seeb remix) vs. Lean On",:song_api => "https://soundcloud.com/melenium/lean-on-vs-itapii",:genre => "EDM",:artist => "MELENIUM")
Music.create(:song_name => "Vanic X Tove Styrke - Borderline",:song_api => "https://soundcloud.com/djvanic/vanic-x-tove-styrke-borderline",:genre => "EDM",:artist => "Vanic")
Music.create(:song_name => "Bryce Fox - Burn Fast (Koni Remix)",:song_api => "https://soundcloud.com/koni_music/bryce-fox-burn-fast-koni-remix-1",:genre => "Disco",:artist => "Koni")
Music.create(:song_name => "Throttle x Earth, Wind & Fire - September",:song_api => "https://soundcloud.com/throttle/throttle-x-earth-wind-fire-september",:genre => "Disco",:artist => "Throttle")
Music.create(:song_name => "Ain't Nobody",:song_api => "https://soundcloud.com/route94/aint-nobody",:genre => "Disco",:artist => "Route94")
Music.create(:song_name => "Maroon 5 feat Wiz Khalifa - Payphone (Matoma Remix)",:song_api => "https://soundcloud.com/matoma-official/payphone-matoma-remix",:genre => "Disco",:artist => "Matoma")
Music.create(:song_name => "NU DISCO / INDIE DANCE SET 1 - AHMET KILIC",:song_api => "https://soundcloud.com/ahmet-kilic/nu-disco-indie-dance-set-ahmet-kilic",:genre => "Disco",:artist => "Ahmet Kılıç")
Music.create(:song_name => "Sometime (feat. Brasstracks)",:song_api => "https://soundcloud.com/yungestbae/sometime",:genre => "Disco",:artist => "YUNG BAE")
Music.create(:song_name => "WRLD - Chase It (feat. Savoi)",:song_api => "https://soundcloud.com/monstercat/wrld-chase-it",:genre => "Disco",:artist => "Monstercat")
Music.create(:song_name => "Whitney Houston - How Will I Know (Oliver Nelson Remix)",:song_api => "https://soundcloud.com/olivernelson/whitney-houston-how-will-i",:genre => "Disco",:artist => "Oliver Nelson")
Music.create(:song_name => "DJ BRAVO (Champion) new song 2016",:song_api => "https://soundcloud.com/shafin-baloch-77759325/dj-bravo-champion-new-song-2016",:genre => "Disco",:artist => "DJ Bravo")
Music.create(:song_name => "Calvin Harris & Disciples - How Deep Is Your Love (Liva K Remix)| Free Download",:song_api => "https://soundcloud.com/liva-k/calvin-harris-disciples-how-deep-is-your-love-liva-k-remix-free-download",:genre => "Disco",:artist => "Liva K")
Music.create(:song_name => "Mateo Roksandic Feat. Demmy Sober - Me & You (Original Mix)",:song_api => "https://soundcloud.com/spiritsoulrecords/mateo-roksandic-feat-demmy-sober-me-you-original-mix",:genre => "Disco",:artist => "Spirit Soul Records")
Music.create(:song_name => "Childish Gambino - Sober (Oliver Nelson Remix)",:song_api => "https://soundcloud.com/perfecthavocmixtapes/childish-gambino-sober-oliver-nelson-remix",:genre => "Disco",:artist => "Perfect Havoc Mixtapes")
Music.create(:song_name => "selfish high heels (w/ harrison & マクロスMACROSS 82-99)",:song_api => "https://soundcloud.com/yungestbae/selfish-high-heels",:genre => "Disco",:artist => "YUNG BAE")
Music.create(:song_name => "Live My Life - Far East Movement",:song_api => "https://soundcloud.com/mert882/live-my-life-far-east-movement",:genre => "Disco",:artist => "mert882")
Music.create(:song_name => "We Don't Talk Anymore Edit",:song_api => "https://soundcloud.com/jaz_s/we-dont-talk-anymore-vs-love-me-harder-mashup",:genre => "Pop",:artist => "Jaz ♛")
Music.create(:song_name => "Hello - Adele",:song_api => "https://soundcloud.com/gracedaviesofficial/hello-adele",:genre => "Pop",:artist => "Grace Davies")
Music.create(:song_name => "Lorde - Tennis Court (Flume Remix)",:song_api => "https://soundcloud.com/flume/lorde-tennis-court-flume-remix",:genre => "Pop",:artist => "Flume")
Music.create(:song_name => "Love Yourself - Justin Bieber",:song_api => "https://soundcloud.com/khamari-barnes/love-yourself-justin-bieber",:genre => "Pop",:artist => "Justin Bieber")
Music.create(:song_name => "The Weekend, Wicked Games",:song_api => "https://soundcloud.com/fadermedia/the-weekend-wicked-games",:genre => "Pop",:artist => "The FADER")
Music.create(:song_name => "Marvin Gaye ft. Meghan Trainor",:song_api => "https://soundcloud.com/charlieputh/marvin-gaye-ft-meghan-trainor",:genre => "Pop",:artist => "Charlie Puth")
